ROKU CAST APP 21E7 CRASH === PixelPlayer Crash Report === Date: 12/05/2026 20:11:23 Exception: dq0
Stack Trace:
java.lang.NoClassDefFoundError: dq0
at p42.<init>(Unknown Source:3)
at p42.<init>(SourceFile:59)
at q73.<init>(Unknown Source:5)
at c1.a(Unknown Source:166)
at mv6.a(Unknown Source:82)
at d90.a(Unknown Source:41)
at wg6.p(Unknown Source:93)
at wg6.invokeSuspend(Unknown Source:101)
at hf0.resumeWith(Unknown Source:7)
at yi2.run(Unknown Source:110)
at tq3.run(Unknown Source:373)
at d1a.run(Unknown Source:2)
at xt1.run(Unknown Source:86)
Suppressed: fh2: [wo9{Cancelling}@cd8f7e8, Dispatchers.Main.immediate]
Caused by: java.lang.ExceptionInInitializerError
at jq0.<clinit>(Unknown Source:123)
at dq0.<clinit>(Unknown Source:0)
at p42.<init>(Unknown Source:3)
at tx6.<init>(Unknown Source:8)
at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(Unknown Source:23)
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
at c1.a(Unknown Source:62)
... 9 more
Caused by: java.lang.IllegalArgumentException: Can't find '[toLeakAwareBuffer]' in e1
at xha.n(Unknown Source:12)
at am8.a(Unknown Source:122)
at e1.<clinit>(Unknown Source:8)
... 17 more